### PR TITLE
fix: add font-family to everything

### LINKED ISSUE #208: Button not using theme font
The font applied is `system-ui` from the browser's default stylesheet.
The font should be taken from the theme instead.

### PR DESCRIPTION
**Pull request by varl**
Fixes #208.

### CODE REVIEW

File: .storybook/reset-decorator.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import React from 'react'
+
+import { CssReset } from '../src'
+
+const CssResetWrapper = fn => (
+    <div style={{ margin: '10px' }}>
```
Comment (Mohammer5) [inline .storybook/reset-decorator.js]: It's completely irrelevant, but you could just write `margin: 10`, instead of `margin: '10px'`. For the lazy people ;) No need to change anything here!
